DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;

CREATE TABLE IF NOT EXISTS users(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name  VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL,
CONSTRAINT pk_user PRIMARY KEY (id),
CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
CONSTRAINT pk_category PRIMARY KEY (id),
CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
annotation VARCHAR(2000) NOT NULL,
category_id BIGINT NOT NULL,
created_on TIMESTAMP NOT NULL,
description VARCHAR(7000),
event_date TIMESTAMP NOT NULL,
initiator_id BIGINT NOT NULL,
lat FLOAT,
lon FLOAT,
paid BOOLEAN NOT NULL,
participant_limit INT NOT NULL,
published_on TIMESTAMP,
request_moderation BOOLEAN NOT NULL,
state VARCHAR(30) NOT NULL,
title varchar(120) NOT NULL,
confirmed_requests INT,
CONSTRAINT pk_events PRIMARY KEY (id),
CONSTRAINT fl_events_to_categories FOREIGN KEY (category_id) REFERENCES categories (id),
CONSTRAINT fl_events_to_users FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
created TIMESTAMP,
event_id BIGINT,
requester_id BIGINT,
status VARCHAR(255) NOT NULL,
CONSTRAINT pk_request PRIMARY KEY (id),
CONSTRAINT fk_requests_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
CONSTRAINT fk_requests_to_users FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
CONSTRAINT uq_requester_event UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
pinned BOOLEAN NOT NULL,
title VARCHAR(50) NOT NULL,
CONSTRAINT pk_compilation PRIMARY KEY (id),
CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events(
compilation_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
CONSTRAINT fk_comp_events_to_compilations FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
CONSTRAINT fk_comp_events_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);